services:

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - 80:8080
    depends_on:
      - producer
      - consumer
    networks:
      - mamazone

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      - producer
      - postgres
    networks:
      - mamazone

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      - postgres
    networks:
      - mamazone

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mamazone
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

networks:
  mamazone:
    driver: bridge

volumes:
  postgres_data: