bus:
  event:
    socket:
      server:
        port: ${SOCKET_EVENT_BUS_PORT}

producer:
  bus:
    command:
      socket:
        host: ${SOCKET_COMMAND_BUS_HOST}
        port: ${SOCKET_COMMAND_BUS_PORT}

spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}