bus:
  event:
    socket:
      server:
        port: 10003

#producer:
#  bus:
#    command:
#      socket:
#        host: localhost
#        port: 10001

spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}